services:
  backend:
    image: ghcr.io/matt0pena0/adm_taxis/backend:latest
    restart: unless-stopped
    volumes:
      - ./backend/data:/app/data
    expose:
      - "8000"
    networks:
      - internal

  frontend:
    image: ghcr.io/matt0pena0/adm_taxis/frontend:latest
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - internal
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: adm_taxis-nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx-prod.conf:/etc/nginx/nginx.conf:ro
    expose:
      - "80"
    networks:
      - internal
      - proxy_net
    depends_on:
      - backend
      - frontend

networks:
  internal:
    driver: bridge
  proxy_net:
    external: true
